import "@/app/globals.css"
import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'Techstatic 2024 - A Digital Odyssey',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html crossOrigin="anonymous" lang="en">
      <body>
          {children}
      </body>
    </html>
  )
}
