import "@/app/globals.css"
import * as THREE from "three";
import perlin, { material, options } from "../app/perlin";

export const metadata = {
  title: 'Techstatic 2024 - A Digital Odyssey',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html crossOrigin="anonymous" lang="en">
      <body className={inter.className}>
          {children}

      </body>
    </html>
  )
}
