import { Inter } from 'next/font/google'
import './globals.css'
import Background from '@/components/Background'
import IndexPage from '@/pages'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Techstatic 2024 - A Digital Odyssey',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html crossorigin="anonymous" lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
